version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/html-webpack-externals-plugin

    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: npm-test
          command: npm test
      - deploy:
          name: npm-publish
          command: if [ "${CIRCLE_TAG}" == v* ]; then npm publish; fi
