version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/html-webpack-externals-plugin

    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm test
      - deploy: if [ "${CIRCLE_TAG}" == v* ]; then npm publish; fi
