version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/html-webpack-externals-plugin

    steps:
      - checkout
      - run:
          name: update-npm
          command: |
            npm install npm@latest --no-save &&
            sudo rm -rf /usr/local/lib/node_modules/npm &&
            sudo mv node_modules/npm /usr/local/lib/node_modules/npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: install-peer-dependencies
          command: npm install webpack@^3.0.0 html-webpack-plugin@^2.0.0 --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - deploy:
          name: publish
          command: if [ "${CIRCLE_TAG}" == v* ]; then npm publish; fi
